package view;

import javax.swing.JOptionPane;

import dao.ProfessorDAO;
import model.Professor;

import utils.Constantes;
import utils.LookAndFeelHelper;
import utils.ValidadorInput;
import utils.ViewUtils;

public class CadastroProfessor extends javax.swing.JFrame {

    private final transient ProfessorDAO professorDAO;

    public CadastroProfessor() throws java.text.ParseException {
        initComponents();
        formatarCampos();
        javax.swing.JButton bConfirmar = ViewUtils.criarBotao(Constantes.UIConstants.BTN_CONFIRMAR, this::bConfirmarActionPerformed);
        getRootPane().setDefaultButton(bConfirmar);
        this.professorDAO = new ProfessorDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel lblTitulo = ViewUtils.criarLabelTitulo("Cadastro de Professor")
        ;
        nome = new javax.swing.JTextField();
        campus = new javax.swing.JComboBox<>();
        javax.swing.JLabel lblNome = new javax.swing.JLabel();
        javax.swing.JLabel lblCampus = ViewUtils.criarLabel(Constantes.UIConstants.CAMPUS, "lblCampus");
        javax.swing.JButton bCancelar = ViewUtils.criarBotao(Constantes.UIConstants.BTN_CANCELAR, this::bCancelarActionPerformed);
        javax.swing.JButton bConfirmar = ViewUtils.criarBotao(Constantes.UIConstants.BTN_CONFIRMAR, this::bConfirmarActionPerformed);
        titulo = new javax.swing.JComboBox<>();
        javax.swing.JLabel lblTituloProfessor = ViewUtils.criarLabel(Constantes.UIConstants.TITULO, "lblTituloProfessor");
        idade = new com.toedter.calendar.JDateChooser();
        javax.swing.JLabel lblNascimento = ViewUtils.criarLabel(Constantes.UIConstants.NASCIMENTO, "lblNascimento");
        cpfFormatado = new javax.swing.JFormattedTextField();
        javax.swing.JLabel lblCPF = ViewUtils.criarLabel(Constantes.UIConstants.CPF, "lblCPF");
        javax.swing.JLabel lblContato = ViewUtils.criarLabel(Constantes.UIConstants.CONTATO, "lblContato");
        salarioFormatado = new javax.swing.JFormattedTextField();
        javax.swing.JLabel lblSalario = ViewUtils.criarLabel(Constantes.UIConstants.SALARIO, "lblSalario");
        contatoFormatado = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Professor");
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastro de Professor");

        campus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Continente", "Dib Mussi", "Ilha", "Pedra Branca", "Trajano", "Tubarão" }));
        campus.setName(""); // NOI18N

        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNome.setText("Nome:");

        lblCampus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCampus.setText("Campus:");

        bCancelar.setText("Cancelar");

        bConfirmar.setText("Confirmar");
        bConfirmar.setToolTipText("ENTER");

        titulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Graduação", "Especialização", "Mestrado", "Doutorado" }));

        lblTituloProfessor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTituloProfessor.setText("Título:");

        idade.setBackground(new java.awt.Color(153, 153, 153));
        idade.setForeground(new java.awt.Color(51, 51, 51));

        lblNascimento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNascimento.setText("Nasc.:");

        lblCPF.setText("CPF:");

        lblContato.setText("Contato:");

        lblSalario.setText("Salário:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTituloProfessor)
                                    .addComponent(lblNascimento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblSalario)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(salarioFormatado, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNome)
                                    .addComponent(lblCampus)
                                    .addComponent(lblCPF))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nome)
                                    .addComponent(campus, 0, 282, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cpfFormatado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblContato)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(contatoFormatado, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCampus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfFormatado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCPF)
                    .addComponent(lblContato)
                    .addComponent(contatoFormatado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNascimento)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(salarioFormatado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSalario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloProfessor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formatarCampos() throws java.text.ParseException {
        try {
            ValidadorInput.aplicarFormatacaoProfessor(cpfFormatado, contatoFormatado, salarioFormatado);
        } catch (java.text.ParseException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao formatar campos", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private String validarCpf() throws Mensagens {
        String cpfLimpo = ValidadorInput.validarTamanhoNumericoFixo(this.cpfFormatado.getText(), 11, "CPF");

        if (this.professorDAO.existeCpf(cpfLimpo)) {
            throw new Mensagens("CPF já cadastrado no sistema");
        }
        return cpfLimpo;
    }

    private void bConfirmarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bConfirmarActionPerformed

        try {

            String nomeProfessor = ValidadorInput.validarNome(this.nome.getText(), 2);
            String campusProfessor = ValidadorInput.validarSelecaoComboBox(this.campus.getSelectedIndex(),
                    Constantes.getCampus(), "Campus");
            String cpfProfessor = validarCpf();
            String contatoProfessor = ValidadorInput.validarTamanhoNumericoFixo(this.contatoFormatado.getText(), 11,
                    "Contato");
            int idadeProfessor = ValidadorInput.validarIdadePorData(this.idade.getDate(), 11);
            double salarioProfessor = ValidadorInput.validarSalario(this.salarioFormatado, 4);
            String tituloProfessor = ValidadorInput.validarSelecaoComboBox(this.titulo.getSelectedIndex(),
                    Constantes.getTitulos(), "Título");

            model.ProfessorDTO dto = new model.ProfessorDTO();
            dto.setCampus(campusProfessor);
            dto.setCpf(cpfProfessor);
            dto.setContato(contatoProfessor);
            dto.setTitulo(tituloProfessor);
            dto.setSalario(salarioProfessor);
            dto.setNome(nomeProfessor);
            dto.setIdade(idadeProfessor);
            dto.setId(0);
            Professor novoProfessor = new Professor(dto);

            // Adicionando dados validados no database usando o DAO
            if (this.professorDAO.insert(novoProfessor)) {
                JOptionPane.showMessageDialog(rootPane,
                        "Professor cadastrado com sucesso! ID: " + novoProfessor.getId());

                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar professor no banco de dados.");
            }

            // Capturando exceções    
        } catch (Exception ex) {
            ViewUtils.tratarErroCadastro(ex);
        }

    }// GEN-LAST:event_bConfirmarActionPerformed

    /**
     * Método vinculado automaticamente ao evento ActionListener do botão
     * bCancelar. O vínculo é definido no arquivo .form e invocado em tempo de
     * execução pelo Swing.
     */
    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bCancelarActionPerformed
        ViewUtils.fecharJanelaAoCancelar(evt.getSource(), this);

    }// GEN-LAST:event_bCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        LookAndFeelHelper.aplicarNimbus();
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new CadastroProfessor().setVisible(true);
            } catch (java.text.ParseException ex) {
                java.util.logging.Logger.getLogger(CadastroProfessor.class.getName())
                        .log(java.util.logging.Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> campus;
    private javax.swing.JFormattedTextField contatoFormatado;
    private javax.swing.JFormattedTextField cpfFormatado;
    private com.toedter.calendar.JDateChooser idade;
    private javax.swing.JTextField nome;
    private javax.swing.JFormattedTextField salarioFormatado;
    private javax.swing.JComboBox<String> titulo;
    // End of variables declaration//GEN-END:variables
}
