package view;

import dao.ProfessorDAO;
import model.Professor;
import model.ProfessorDTO;
import utils.Constantes;
import utils.LookAndFeelHelper;
import utils.ValidadorInput;
import utils.ViewUtils;

import java.text.ParseException;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

public class EditarProfessor extends javax.swing.JFrame {

	private final transient ProfessorDAO professorDAO;
	private final String[] dadosProfessor;

	private static final List<String> LISTA_CAMPUS = Constantes.getCampus();
	private static final List<String> LISTA_TITULOS = Constantes.getTitulos();

	public EditarProfessor() throws ParseException {
		initComponents();
		aplicarMascaras();
		this.professorDAO = new ProfessorDAO();
		this.dadosProfessor = null;

		getRootPane().setDefaultButton(bConfirmar);

	}

	public EditarProfessor(String[] dadosParaEdicao) throws ParseException {
		initComponents();
		aplicarMascaras();
		this.professorDAO = new ProfessorDAO();
		this.dadosProfessor = dadosParaEdicao;

		preencheCampos();
		getRootPane().setDefaultButton(bConfirmar);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		nome = new javax.swing.JTextField();
		campus = new javax.swing.JComboBox<>();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		bCancelar = new javax.swing.JButton();
		bConfirmar = new javax.swing.JButton();
		titulo = new javax.swing.JComboBox<>();
		jLabel6 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		cpfFormatado = new javax.swing.JFormattedTextField();
		jLabel9 = new javax.swing.JLabel();
		salarioFormatado = new javax.swing.JFormattedTextField();
		jLabel5 = new javax.swing.JLabel();
		idade = new javax.swing.JTextField();
		contatoFormatado = new javax.swing.JFormattedTextField();
		jLabel7 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Editar Professor");
		setResizable(false);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Editar Professor");

		campus.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "-", "Continente", "Dib Mussi", "Ilha", "Pedra Branca", "Trajano", "Tubarão" }));
		campus.setName(""); // NOI18N

		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabel2.setText("Nome:");

		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabel3.setText("Campus:");

		bCancelar.setText("Cancelar");
		bCancelar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bCancelarActionPerformed(evt);
			}
		});

		bConfirmar.setText("Confirmar");
		bConfirmar.setToolTipText("ENTER");
		bConfirmar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bConfirmarActionPerformed(evt);
			}
		});

		titulo.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "-", "Graduação", "Especialização", "Mestrado", "Doutorado" }));

		jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabel6.setText("Título:");

		jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabel8.setText("Idade:");

		jLabel9.setText("CPF:");

		jLabel5.setText("Salário:");

		jLabel7.setText("Contato:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup().addGap(29, 29, 29).addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel6).addComponent(jLabel8))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addComponent(bConfirmar,
																javax.swing.GroupLayout.PREFERRED_SIZE, 108,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(66, 66, 66).addComponent(bCancelar,
																javax.swing.GroupLayout.PREFERRED_SIZE, 108,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE,
																282, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(layout.createSequentialGroup()
																.addComponent(idade,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 108,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(jLabel5)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(salarioFormatado,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 104,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))))
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel2).addComponent(jLabel3).addComponent(jLabel9))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(nome).addComponent(campus, 0, 282, Short.MAX_VALUE)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
														.createSequentialGroup().addComponent(cpfFormatado)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(jLabel7)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(contatoFormatado,
																javax.swing.GroupLayout.PREFERRED_SIZE, 104,
																javax.swing.GroupLayout.PREFERRED_SIZE)))))
								.addGap(0, 0, Short.MAX_VALUE)))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addComponent(
						jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel2))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(campus, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel3))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(cpfFormatado, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel9)
						.addComponent(contatoFormatado, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel7))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel8).addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(salarioFormatado, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel5)))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel6))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(bConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(29, 29, 29)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	// --- FORMATAÇÃO DOS CAMPOS (MÁSCARAS IGUAL AO ORIGINAL) ---
	private void aplicarMascaras() throws ParseException {
		MaskFormatter cpf = new MaskFormatter("###.###.###-##");
		cpf.install(cpfFormatado);

		MaskFormatter contato = new MaskFormatter("(##) # ####-####");
		contato.install(contatoFormatado);

		// máscara idêntica ao original
		MaskFormatter salario = new MaskFormatter("R$#####");
		salario.install(salarioFormatado);
	}

	// --- PREENCHE CAMPOS COMO NO ORIGINAL ---
	private void preencheCampos() {
		this.nome.setText(dadosProfessor[0]);
		this.idade.setText(dadosProfessor[1]);

		int idxCampus = LISTA_CAMPUS.indexOf(dadosProfessor[2]);
		if (idxCampus < 0)
			idxCampus = 0;
		this.campus.setSelectedIndex(idxCampus);

		this.cpfFormatado.setText(dadosProfessor[3]);
		this.contatoFormatado.setText(dadosProfessor[4]);

		int idxTitulo = LISTA_TITULOS.indexOf(dadosProfessor[5]);
		if (idxTitulo < 0)
			idxTitulo = 0;
		this.titulo.setSelectedIndex(idxTitulo);

		// salário vem como texto do tipo 12345
		String salarioOriginal = dadosProfessor[6].replace("R$", "");
		this.salarioFormatado.setText("R$" + salarioOriginal);
	}

	// ===================================================================================
	// =========================== VALIDAÇÕES INDIVIDUAIS
	// ================================
	// ===================================================================================

	private String validarNome() throws Mensagens {
		return ValidadorInput.validarNome(this.nome.getText(), 2);
	}

	private String validarCampus() throws Mensagens {
		return ValidadorInput.validarSelecaoComboBox(this.campus.getSelectedIndex(), LISTA_CAMPUS, "Campus");
	}

	private String validarTitulo() throws Mensagens {
		return ValidadorInput.validarSelecaoComboBox(this.titulo.getSelectedIndex(), LISTA_TITULOS, "Título");
	}

	private String validarCpf() throws Mensagens {
		String cpf = ValidadorInput.validarTamanhoNumericoFixo(this.cpfFormatado.getText(), 11, "CPF");

		int idAtual = Integer.parseInt(dadosProfessor[7]);
		if (professorDAO.existeCpf(cpf, idAtual)) {
			throw new Mensagens("CPF já cadastrado no sistema");
		}
		return cpf;
	}

	private String validarContato() throws Mensagens {
		return ValidadorInput.validarTamanhoNumericoFixo(this.contatoFormatado.getText(), 11, "Contato");
	}

	private int validarIdade() throws Mensagens {
		String texto = idade.getText();

		if (texto.isEmpty())
			throw new Mensagens("Idade não pode ser vazia");

		int idadeInt = Integer.parseInt(texto);

		// regra do original:
		if (idadeInt < 11)
			throw new Mensagens("Idade inválida");

		return idadeInt;
	}

	private double validarSalario() throws Mensagens {
		// remove TUDO que não é número (R$, espaço, máscara)
		String limpo = salarioFormatado.getText().replaceAll("[^0-9]", "");

		if (limpo.length() < 4) {
			throw new Mensagens("O salário deve ter pelo menos 4 dígitos");
		}

		return Double.parseDouble(limpo);
	}

	// ===================================================================================
	// ================================ AÇÃO DO BOTÃO
	// ====================================
	// ===================================================================================

	private void bConfirmarActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			int id = Integer.parseInt(dadosProfessor[7]);

			String nomeValidado = validarNome();
			String campusVal = validarCampus();
			String cpfVal = validarCpf();
			String contatoVal = validarContato();
			int idadeVal = validarIdade();
			double salarioVal = validarSalario();
			String tituloVal = validarTitulo();

			// cria DTO
			ProfessorDTO dto = new ProfessorDTO();
			dto.setId(id);
			dto.setNome(nomeValidado);
			dto.setIdade(idadeVal);
			dto.setCpf(cpfVal);
			dto.setContato(contatoVal);
			dto.setCampus(campusVal);
			dto.setTitulo(tituloVal);
			dto.setSalario(salarioVal);

			Professor atualizado = new Professor(dto);

			if (this.professorDAO.update(atualizado)) {
				JOptionPane.showMessageDialog(rootPane, "Professor alterado com sucesso!");
				this.dispose();
			} else {
				JOptionPane.showMessageDialog(rootPane, "Erro ao atualizar professor no banco!");
			}

		} catch (Mensagens e) {
			JOptionPane.showMessageDialog(rootPane, e.getMessage());
		} catch (Exception e) {
			JOptionPane.showMessageDialog(rootPane, "Erro inesperado: " + e.getMessage());
		}
	}

	private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {
		ViewUtils.fecharJanelaAoCancelar(evt.getSource(), this);
	}

	public static void main(String[] args) {
		LookAndFeelHelper.aplicarNimbus();
		java.awt.EventQueue.invokeLater(() -> {
			try {
				new EditarProfessor().setVisible(true);
			} catch (Exception e) {
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton bCancelar;
	private javax.swing.JButton bConfirmar;
	private javax.swing.JComboBox<String> campus;
	private javax.swing.JFormattedTextField contatoFormatado;
	private javax.swing.JFormattedTextField cpfFormatado;
	private javax.swing.JTextField idade;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField nome;
	private javax.swing.JFormattedTextField salarioFormatado;
	private javax.swing.JComboBox<String> titulo;
	// End of variables declaration//GEN-END:variables
}
