package view;

import java.util.List;

import javax.swing.JOptionPane;

import dao.ProfessorDAO;
import model.Professor;
import utils.Constantes;
import utils.LookAndFeelHelper;
import utils.ValidadorInput;
import utils.ViewUtils;

public class EditarProfessor extends javax.swing.JFrame {

    private final transient ProfessorDAO professorDAO;
    private final String[] dadosProfessor;

    private static final List<String> LISTA_CAMPUS = Constantes.getCampus();
    private static final List<String> LISTA_TITULOS = Constantes.getTitulos();

    public EditarProfessor() throws java.text.ParseException {
        initComponents();
        formatarCampos();
        this.professorDAO = new ProfessorDAO();
        this.dadosProfessor = null;

        javax.swing.JButton bConfirmar = ViewUtils.criarBotao(Constantes.UIConstants.BTN_CONFIRMAR, this::bConfirmarActionPerformed);
        getRootPane().setDefaultButton(bConfirmar);
    }

    public EditarProfessor(String[] dadosParaEdicao) throws java.text.ParseException {
        this.dadosProfessor = dadosParaEdicao;
        this.professorDAO = new ProfessorDAO();

        initComponents();
        formatarCampos();
        preencheCampos();

        javax.swing.JButton bConfirmar = ViewUtils.criarBotao(Constantes.UIConstants.BTN_CONFIRMAR, this::bConfirmarActionPerformed);
        getRootPane().setDefaultButton(bConfirmar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel lblTitulo = ViewUtils.criarLabelTitulo(Constantes.UIConstants.TITULO_EDITAR_PROFESSOR);
        nome = new javax.swing.JTextField();
        campus = new javax.swing.JComboBox<>();
        javax.swing.JLabel lblNome = ViewUtils.criarLabel(Constantes.UIConstants.NOME, "lblNome");
        javax.swing.JLabel lblCampus = ViewUtils.criarLabel(Constantes.UIConstants.CAMPUS, "lblCampus");
        javax.swing.JButton bCancelar = ViewUtils.criarBotao(Constantes.UIConstants.BTN_CANCELAR, this::bCancelarActionPerformed);
        javax.swing.JButton bConfirmar = ViewUtils.criarBotao(Constantes.UIConstants.BTN_CONFIRMAR, this::bConfirmarActionPerformed);
        titulo = new javax.swing.JComboBox<>();
        javax.swing.JLabel lblTituloProfessor = ViewUtils.criarLabel(Constantes.UIConstants.TITULO, "lblTituloProfessor");
        javax.swing.JLabel lblIdade = ViewUtils.criarLabel(Constantes.UIConstants.IDADE, "lblIdade");
        cpfFormatado = new javax.swing.JFormattedTextField();
        javax.swing.JLabel lblCPF = ViewUtils.criarLabel(Constantes.UIConstants.CPF, "lblCPF");
        salarioFormatado = new javax.swing.JFormattedTextField();
        javax.swing.JLabel lblSalario = ViewUtils.criarLabel(Constantes.UIConstants.SALARIO, "lblSalario");
        idade = new javax.swing.JTextField();
        contatoFormatado = new javax.swing.JFormattedTextField();
        javax.swing.JLabel lblContato = ViewUtils.criarLabel(Constantes.UIConstants.CONTATO, "lblContato");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Professor");
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Editar Professor");

        campus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Continente", "Dib Mussi", "Ilha", "Pedra Branca", "Trajano", "Tubarão" }));
        campus.setName(""); // NOI18N

        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNome.setText("Nome:");

        lblCampus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCampus.setText("Campus:");

        bCancelar.setText("Cancelar");

        bConfirmar.setText("Confirmar");
        bConfirmar.setToolTipText("ENTER");

        titulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Graduação", "Especialização", "Mestrado", "Doutorado" }));

        lblTituloProfessor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTituloProfessor.setText("Título:");

        lblIdade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIdade.setText("Idade:");

        lblCPF.setText("CPF:");

        lblSalario.setText("Salário:");

        lblContato.setText("Contato:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTituloProfessor)
                                    .addComponent(lblIdade))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblSalario)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(salarioFormatado, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNome)
                                    .addComponent(lblCampus)
                                    .addComponent(lblCPF))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nome)
                                    .addComponent(campus, 0, 282, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cpfFormatado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblContato)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(contatoFormatado, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCampus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfFormatado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCPF)
                    .addComponent(contatoFormatado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIdade)
                        .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(salarioFormatado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSalario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloProfessor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formatarCampos() throws java.text.ParseException {
        try {
            ValidadorInput.aplicarFormatacaoProfessor(cpfFormatado, contatoFormatado, salarioFormatado);
        } catch (java.text.ParseException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao formatar campos", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void preencheCampos() {
        int indexCampus = 0;
        int indexTitulo = 0;

        for (int i = 0; i < LISTA_CAMPUS.size(); i++) {
            if (dadosProfessor[2].equalsIgnoreCase(LISTA_CAMPUS.get(i))) {
                indexCampus = i;
            }
        }

        for (int i = 0; i < LISTA_TITULOS.size(); i++) {
            if (dadosProfessor[5].equalsIgnoreCase(LISTA_TITULOS.get(i))) {
                indexTitulo = i;
            }
        }

        this.nome.setText(dadosProfessor[0]);
        this.idade.setText(dadosProfessor[1]);
        this.campus.setSelectedIndex(indexCampus);
        this.cpfFormatado.setText(dadosProfessor[3]);
        this.contatoFormatado.setText(dadosProfessor[4]);
        this.titulo.setSelectedIndex(indexTitulo);

        try {
            double salario = Double.parseDouble(dadosProfessor[6]);
            this.salarioFormatado.setValue(salario);
        } catch (NumberFormatException e) {
            this.salarioFormatado.setValue(0.0);
        }
    }

    private void bConfirmarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bConfirmarActionPerformed
        try {
            int id = Integer.parseInt(dadosProfessor[7]);

            String campusSelecionado = validarCampus();
            String nomeDigitado = validarNome();
            String cpfValidado = validarCpf();
            String contatoValidado = validarContato();
            int idadeValidada = validarIdade();
            double salario = ValidadorInput.validarSalario(this.salarioFormatado, 4);
            String tituloSelecionado = validarTitulo();

            model.ProfessorDTO dto = new model.ProfessorDTO();
            dto.setCampus(campusSelecionado);
            dto.setCpf(cpfValidado);
            dto.setContato(contatoValidado);
            dto.setTitulo(tituloSelecionado);
            dto.setSalario(salario);
            dto.setId(id);
            dto.setNome(nomeDigitado);
            dto.setIdade(idadeValidada);

            Professor professorAtualizado = new Professor(dto);

            if (this.professorDAO.update(professorAtualizado)) {
                JOptionPane.showMessageDialog(rootPane, "Professor alterado com sucesso");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao alterar professor no banco de dados");
            }
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(rootPane, "Informe um número");
        }
    }// GEN-LAST:event_bConfirmarActionPerformed

    /**
     * Método vinculado automaticamente ao evento ActionListener do botão
     * bCancelar. O vínculo é definido no arquivo .form através do atributo:
     * handler="bCancelarActionPerformed". Este método é executado em tempo de
     * execução pelo Swing e não deve ser removido.
     */
    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bCancelarActionPerformed
        ViewUtils.fecharJanelaAoCancelar(evt.getSource(), this);

    }// GEN-LAST:event_bCancelarActionPerformed

    // Métodos Auxiliares
    private String validarCampus() throws Mensagens {
        return ValidadorInput.validarSelecaoComboBox(this.campus.getSelectedIndex(), LISTA_CAMPUS, "Campus");
    }

    private String validarTitulo() throws Mensagens {
        return ValidadorInput.validarSelecaoComboBox(this.titulo.getSelectedIndex(), LISTA_TITULOS, "Título");
    }

    private String validarNome() throws Mensagens {
        return ValidadorInput.validarNome(this.nome.getText(), 2);
    }

    private String validarCpf() throws Mensagens {
        String cpfLimpo = ValidadorInput.validarTamanhoNumericoFixo(this.cpfFormatado.getText(), 11, "CPF");

        int idAtual = Integer.parseInt(dadosProfessor[7]);
        if (professorDAO.existeCpf(cpfLimpo, idAtual)) {
            throw new Mensagens("CPF já cadastrado no sistema");
        }

        return cpfLimpo;
    }

    private String validarContato() throws Mensagens {
        return ValidadorInput.validarTamanhoNumericoFixo(this.contatoFormatado.getText(), 11, "Contato");
    }

    private int validarIdade() throws Mensagens {
        String inputIdade = this.idade.getText();

        if (inputIdade.isEmpty()) {
            throw new Mensagens("Idade não pode ser vazia");
        }

        return ValidadorInput.validarTamanhoMinimoNumerico(inputIdade, 11);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        LookAndFeelHelper.aplicarNimbus();
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new EditarProfessor().setVisible(true);
            } catch (java.text.ParseException ex) {
                java.util.logging.Logger.getLogger(EditarProfessor.class.getName()).log(java.util.logging.Level.SEVERE,
                        null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> campus;
    private javax.swing.JFormattedTextField contatoFormatado;
    private javax.swing.JFormattedTextField cpfFormatado;
    private javax.swing.JTextField idade;
    private javax.swing.JTextField nome;
    private javax.swing.JFormattedTextField salarioFormatado;
    private javax.swing.JComboBox<String> titulo;
    // End of variables declaration//GEN-END:variables
}
