package view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import dao.ProfessorDAO;
import model.Professor;
import utils.Constantes;
import utils.LookAndFeelHelper;
import utils.ValidadorInput;
import utils.ViewUtils;

import java.util.ArrayList;

public class EditarProfessor extends javax.swing.JFrame {

	private final transient ProfessorDAO professorDAO;
	private final String[] dadosProfessor;

	private static final String[] ARRAY_CAMPUS = Constantes.CAMPUS;
	private static final String[] ARRAY_TITULOS = Constantes.TITULOS;

	public EditarProfessor() throws java.text.ParseException {
		initComponents();
		formatarCampos();
		this.professorDAO = new ProfessorDAO();
		this.dadosProfessor = null;
		getRootPane().setDefaultButton(this.bConfirmar);
	}

	public EditarProfessor(String[] dadosParaEdicao) throws java.text.ParseException {
		this.dadosProfessor = dadosParaEdicao;
		this.professorDAO = new ProfessorDAO();

		initComponents();
		formatarCampos();
		preencheCampos();
		getRootPane().setDefaultButton(this.bConfirmar);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		nome = new javax.swing.JTextField();
		campus = new javax.swing.JComboBox<>();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		bCancelar = new javax.swing.JButton();
		bConfirmar = new javax.swing.JButton();
		titulo = new javax.swing.JComboBox<>();
		jLabel6 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		cpfFormatado = new javax.swing.JFormattedTextField();
		jLabel9 = new javax.swing.JLabel();
		salarioFormatado = new javax.swing.JFormattedTextField();
		jLabel5 = new javax.swing.JLabel();
		idade = new javax.swing.JTextField();
		contatoFormatado = new javax.swing.JFormattedTextField();
		jLabel7 = new javax.swing.JLabel();

		ViewUtils.configurarJanela(this, "Editar Professor");

		ViewUtils.configurarTitulo(jLabel1, "Editar Professor");

		campus.setModel(new javax.swing.DefaultComboBoxModel<>(utils.Constantes.CAMPUS));

		campus.setName(""); // NOI18N

		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabel2.setText("Nome:");

		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabel3.setText("Campus:");

		ViewUtils.configurarBotaoCancelar(bCancelar, this);

		ViewUtils.configurarBotaoConfirmar(bConfirmar, this::bConfirmarActionPerformed);

		titulo.setModel(new javax.swing.DefaultComboBoxModel<>(utils.Constantes.TITULOS));

		jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabel6.setText("Título:");

		jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabel8.setText("Idade:");

		jLabel9.setText("CPF:");

		jLabel5.setText("Salário:");

		jLabel7.setText("Contato:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup().addGap(29, 29, 29).addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel6).addComponent(jLabel8))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addComponent(bConfirmar,
																javax.swing.GroupLayout.PREFERRED_SIZE, 108,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(66, 66, 66).addComponent(bCancelar,
																javax.swing.GroupLayout.PREFERRED_SIZE, 108,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE,
																282, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(layout.createSequentialGroup()
																.addComponent(idade,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 108,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(jLabel5)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(salarioFormatado,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 104,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))))
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel2).addComponent(jLabel3).addComponent(jLabel9))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(nome).addComponent(campus, 0, 282, Short.MAX_VALUE)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
														.createSequentialGroup().addComponent(cpfFormatado)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(jLabel7)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(contatoFormatado,
																javax.swing.GroupLayout.PREFERRED_SIZE, 104,
																javax.swing.GroupLayout.PREFERRED_SIZE)))))
								.addGap(0, 0, Short.MAX_VALUE)))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addComponent(
						jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel2))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(campus, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel3))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(cpfFormatado, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel9)
						.addComponent(contatoFormatado, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel7))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel8).addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(salarioFormatado, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel5)))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel6))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(bConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(29, 29, 29)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void formatarCampos() throws java.text.ParseException {
		try {
			ValidadorInput.aplicarFormatacaoProfessor(cpfFormatado, contatoFormatado, salarioFormatado);
		} catch (java.text.ParseException ex) {
			JOptionPane.showMessageDialog(rootPane, "Erro ao formatar campos", "ERRO", JOptionPane.ERROR_MESSAGE);
		}
	}

	private boolean verificaCpf(String cpf) {
		ArrayList<Professor> minhalista = professorDAO.getMinhaLista();

		for (Professor a : minhalista) {
			if ((cpf.equals(a.getCpf())) && (a.getId() != Integer.parseInt(dadosProfessor[7]))) {
				return true;
			}
		}
		return false;
	}

	private void preencheCampos() {
		int indexCampus = 0;
		int indexTitulo = 0;

		for (int i = 0; i < ARRAY_CAMPUS.length; i++) {
			if (dadosProfessor[2].equalsIgnoreCase(ARRAY_CAMPUS[i])) {
				indexCampus = i;
			}
		}

		for (int i = 0; i < ARRAY_TITULOS.length; i++) {
			if (dadosProfessor[5].equalsIgnoreCase(ARRAY_TITULOS[i])) {
				indexTitulo = i;
			}
		}

		this.nome.setText(dadosProfessor[0]);
		this.idade.setText(dadosProfessor[1]);
		this.campus.setSelectedIndex(indexCampus);
		this.cpfFormatado.setText(dadosProfessor[3]);
		this.contatoFormatado.setText(dadosProfessor[4]);
		this.titulo.setSelectedIndex(indexTitulo);

		try {
			double salario = Double.parseDouble(dadosProfessor[6]);
			this.salarioFormatado.setValue(salario);
		} catch (NumberFormatException e) {
			this.salarioFormatado.setValue(0.0);
		}
	}

	private void bConfirmarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bConfirmarActionPerformed
		try {
			int id = Integer.parseInt(dadosProfessor[7]);

			String campusSelecionado = validarCampus();
			String nomeDigitado = validarNome();
			String cpfValidado = validarCpf();
			String contatoValidado = validarContato();
			int idadeValidada = validarIdade();
			double salario = ValidadorInput.validarSalario(this.salarioFormatado, 4);
			String tituloSelecionado = validarTitulo();

			Professor.ProfessorDTO dto = new Professor.ProfessorDTO();
			dto.setCampus(campusSelecionado);
			dto.setCpf(cpfValidado);
			dto.setContato(contatoValidado);
			dto.setTitulo(tituloSelecionado);
			dto.setSalario(salario);
			dto.setId(id);
			dto.setNome(nomeDigitado);
			dto.setIdade(idadeValidada);

			Professor professorAtualizado = new Professor(dto);

			if (this.professorDAO.update(professorAtualizado)) {
				JOptionPane.showMessageDialog(rootPane, "Professor alterado com sucesso");
				this.dispose();
			} else {
				JOptionPane.showMessageDialog(rootPane, "Erro ao alterar professor no banco de dados");
			}
		} catch (Mensagens erro) {
			JOptionPane.showMessageDialog(rootPane, erro.getMessage());
		} catch (NumberFormatException erro2) {
			JOptionPane.showMessageDialog(rootPane, "Informe um número");
		}
	}// GEN-LAST:event_bConfirmarActionPerformed

	private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bCancelarActionPerformed
		this.dispose();
	}// GEN-LAST:event_bCancelarActionPerformed

	// Métodos Auxiliares
	private String validarCampus() throws Mensagens {
		return ValidadorInput.validarSelecaoComboBox(this.campus.getSelectedIndex(), ARRAY_CAMPUS, "Campus");
	}

	private String validarTitulo() throws Mensagens {
		return ValidadorInput.validarSelecaoComboBox(this.titulo.getSelectedIndex(), ARRAY_TITULOS, "Título");
	}

	private String validarNome() throws Mensagens {
		return ValidadorInput.validarNome(this.nome.getText(), 2);
	}

	private String validarCpf() throws Mensagens {
		String cpfLimpo = ValidadorInput.validarTamanhoNumericoFixo(this.cpfFormatado.getText(), 11, "CPF");

		if (verificaCpf(cpfLimpo)) {
			throw new Mensagens("CPF já cadastrado no sistema");
		}

		return cpfLimpo;
	}

	private String validarContato() throws Mensagens {
		return ValidadorInput.validarTamanhoNumericoFixo(this.contatoFormatado.getText(), 11, "Contato");
	}

	private int validarIdade() throws Mensagens {
		String inputIdade = this.idade.getText();

		if (inputIdade.isEmpty()) {
			throw new Mensagens("Idade não pode ser vazia");
		}

		return ValidadorInput.validarTamanhoMinimoNumerico(inputIdade, 11);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String[] args) {
		LookAndFeelHelper.aplicarNimbus();
		java.awt.EventQueue.invokeLater(() -> {
			try {
				new EditarProfessor().setVisible(true);
			} catch (java.text.ParseException ex) {
				java.util.logging.Logger.getLogger(EditarProfessor.class.getName()).log(java.util.logging.Level.SEVERE,
						null, ex);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton bCancelar;
	private javax.swing.JButton bConfirmar;
	private javax.swing.JComboBox<String> campus;
	private javax.swing.JFormattedTextField contatoFormatado;
	private javax.swing.JFormattedTextField cpfFormatado;
	private javax.swing.JTextField idade;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField nome;
	private javax.swing.JFormattedTextField salarioFormatado;
	private javax.swing.JComboBox<String> titulo;
	// End of variables declaration//GEN-END:variables
}
