package view;

import dao.AlunoDAO;
import model.Aluno;
import utils.ValidadorInput;
import utils.ViewUtils;
import utils.Constantes;
import utils.LookAndFeelHelper;

import javax.swing.JOptionPane;

public class EditarAluno extends javax.swing.JFrame {

	private final transient AlunoDAO alunoDAO;
	private final String[] dadosAluno;

	public EditarAluno() {
		initComponents();
		this.alunoDAO = new AlunoDAO();
		this.dadosAluno = null;
		getRootPane().setDefaultButton(this.bConfirmar);
	}

	public EditarAluno(String[] dados) {
		initComponents();
		this.alunoDAO = new AlunoDAO();
		this.dadosAluno = dados;
		preencheCampos();
		getRootPane().setDefaultButton(this.bConfirmar);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		nome = new javax.swing.JTextField();
		curso = new javax.swing.JComboBox<>();
		fase = new javax.swing.JComboBox<>();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		bCancelar = new javax.swing.JButton();
		bConfirmar = new javax.swing.JButton();
		idade = new javax.swing.JTextField();

		ViewUtils.configurarTelaEdicao(ViewUtils.TelaCadastroConfig.builder().tela(this).tituloLabel(jLabel1)
				.tituloTexto("Editar Aluno").combo1(curso).combo2(fase).botaoCancelar(bCancelar)
				.botaoConfirmar(bConfirmar).acaoConfirmar(this::bConfirmarActionPerformed).build());

		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel2.setText("Nome:");

		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel3.setText("Curso:");

		jLabel4.setText("Idade:");

		jLabel5.setText("Fase:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
				.addGroup(layout.createSequentialGroup().addGap(33, 33, 33)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(nome)
								.addComponent(curso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup()
										.addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, 123,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(jLabel5)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(fase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup()
												.addComponent(bConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(66, 66, 66).addComponent(bCancelar,
														javax.swing.GroupLayout.PREFERRED_SIZE, 108,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(37, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addComponent(
						jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel2))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(curso, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel3))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(fase, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel4).addComponent(jLabel5).addComponent(idade,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(bConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(25, 25, 25)));

		pack();
		setLocationRelativeTo(null);
		java.util.Objects.requireNonNull((java.util.function.Consumer<java.awt.event.ActionEvent>) this::bCancelarActionPerformed);

	}// </editor-fold>//GEN-END:initComponents

	private void preencheCampos() {
		String[] arrayCursos = Constantes.CURSOS;
		int[] arrayFases = Constantes.FASES;

		int indexCursos = 0;
		int indexFases = 0;

		String cursoAluno = this.dadosAluno[3];
		int faseAluno = Integer.parseInt(this.dadosAluno[4]);

		// Busca o índice do curso
		for (int i = 0; i < arrayCursos.length; i++) {
			if (cursoAluno.equalsIgnoreCase(arrayCursos[i])) {
				indexCursos = i;
				break;
			}
		}

		// Busca o índice da fase
		for (int i = 0; i < arrayFases.length; i++) {
			if (faseAluno == arrayFases[i]) {
				indexFases = i;
				break;
			}
		}

		// Preenchimento dos campos
		this.nome.setText(this.dadosAluno[1]);
		this.idade.setText(this.dadosAluno[2]);
		this.curso.setSelectedIndex(indexCursos);
		this.fase.setSelectedIndex(indexFases);
	}

	private void bConfirmarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bConfirmarActionPerformed
		try {
			String[] arrayCursos = Constantes.CURSOS;
			int[] arrayFases = Constantes.FASES;

			// Valida e seta nome
			String nomeAluno = ValidadorInput.validarNome(this.nome.getText(), 2);

			// Valida e seta a idade
			int idadeAluno = ValidadorInput.validarTamanhoMinimoNumerico(this.idade.getText(), 11);

			// Valida e seta o curso
			String cursoAluno = ValidadorInput.validarSelecaoComboBox(this.curso.getSelectedIndex(), arrayCursos,
					"Curso");

			// Valida e seta a fase
			int faseAluno = arrayFases[this.fase.getSelectedIndex()];

			// Busca ID do alubno
			int idAluno = Integer.parseInt(this.dadosAluno[0]);

			// Cria objeto aluno
			Aluno alunoAtualizado = new Aluno(cursoAluno, faseAluno, idAluno, nomeAluno, idadeAluno);

			// Adicionando dados validados no database
			if (this.alunoDAO.update(alunoAtualizado)) { // Usa o método update do DAO
				JOptionPane.showMessageDialog(rootPane, "Aluno alterado com sucesso!");

				this.dispose();
			} else {
				JOptionPane.showMessageDialog(rootPane, "Erro ao alterar aluno no banco de dados.");
			}

			// Capturando exceções
		} catch (Exception ex) {
			ViewUtils.tratarErroCadastro(ex);
		}

	}// GEN-LAST:event_bConfirmarActionPerformed

	/**
	 * Método vinculado automaticamente ao evento ActionListener do botão bCancelar.
	 * O vínculo é definido no arquivo .form e invocado em tempo de execução pelo
	 * Swing.
	 */
	private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bCancelarActionPerformed
		ViewUtils.fecharJanelaAoCancelar(evt.getSource(), this);

	}// GEN-LAST:event_bCancelarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String[] args) {
		LookAndFeelHelper.aplicarNimbus();
		java.awt.EventQueue.invokeLater(() -> new EditarAluno().setVisible(true));
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton bCancelar;
	private javax.swing.JButton bConfirmar;
	private javax.swing.JComboBox<String> curso;
	private javax.swing.JComboBox<String> fase;
	private javax.swing.JTextField idade;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JTextField nome;
	// End of variables declaration//GEN-END:variables
}
