package view;

import utils.Constantes;
import utils.ViewUtils;
import javax.swing.JSeparator;

public class Sobre extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Sobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel lblIntegrante4 = ViewUtils.criarLabel(Constantes.UIConstants.SOBRE_INTEGRANTE_4, "lblIntegrante4");
        javax.swing.JLabel lblIntegrante6 = ViewUtils.criarLabel(Constantes.UIConstants.SOBRE_INTEGRANTE_6, "lblIntegrante6");
        javax.swing.JLabel lblIntegrante1 = ViewUtils.criarLabel(Constantes.UIConstants.SOBRE_INTEGRANTE_1, "lblIntegrante1");
        javax.swing.JLabel lblIntegrante5 = ViewUtils.criarLabel(Constantes.UIConstants.SOBRE_INTEGRANTE_5, "lblIntegrante5");
        javax.swing.JLabel lblIntegrante3 = ViewUtils.criarLabel(Constantes.UIConstants.SOBRE_INTEGRANTE_3, "lblIntegrante3");
        javax.swing.JLabel lblIntegrante2 = ViewUtils.criarLabel(Constantes.UIConstants.SOBRE_INTEGRANTE_2, "lblIntegrante2");
        javax.swing.JLabel lblTitulo = ViewUtils.criarLabelTitulo(Constantes.UIConstants.SOBRE_INSTITUICAO);
        javax.swing.JLabel lblUC = ViewUtils.criarLabel(Constantes.UIConstants.SOBRE_UC, "lblUC");
        javax.swing.JLabel lblCurso = ViewUtils.criarLabel(Constantes.UIConstants.SOBRE_CURSO, "lblCurso");
        javax.swing.JSeparator separadorTopo = new JSeparator();
        javax.swing.JSeparator separadorBase = new JSeparator();
        javax.swing.JLabel lblData = ViewUtils.criarLabel(Constantes.UIConstants.SOBRE_DATA, "lblData");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sobre");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        lblIntegrante4.setText("• Lucas Felipe Rogério");

        lblIntegrante6.setText("• Rade Gabriel Farah ");

        lblIntegrante1.setText("• Camille Zimmermann");

        lblIntegrante5.setText("• Pablo Nevado");

        lblIntegrante3.setText("• Laura Maria Firta Foes");

        lblIntegrante2.setText("• Julia Schaden Exterkoetter");

        lblTitulo.setFont(new java.awt.Font(Constantes.UIConstants.DEFAULT_FONT, java.awt.Font.BOLD, 14)
        );
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("UNIVERSIDADE DO SUL DE SANTA CATARINA");

        lblUC.setFont(new java.awt.Font(Constantes.UIConstants.DEFAULT_FONT, 0, 10));
        lblUC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUC.setText("PROGRAMAÇÃO DE SOLUÇÕES COMPUTACIONAIS");

        lblCurso.setFont(new java.awt.Font(Constantes.UIConstants.DEFAULT_FONT, 0, 10));
        lblCurso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurso.setText("SISTEMAS DE INFORMAÇÃO");

        lblData.setFont(new java.awt.Font(Constantes.UIConstants.DEFAULT_FONT, 1, 12));
        lblData.setText("Florianópolis, 2022");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(separadorTopo)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(separadorBase)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIntegrante2)
                    .addComponent(lblIntegrante1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblIntegrante3)
                        .addGap(21, 21, 21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIntegrante4)
                    .addComponent(lblIntegrante5)
                    .addComponent(lblIntegrante6))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUC, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblData)
                        .addGap(150, 150, 150))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCurso)
                .addGap(18, 18, 18)
                .addComponent(separadorTopo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIntegrante1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIntegrante2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIntegrante3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIntegrante4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIntegrante5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIntegrante6)))
                .addGap(29, 29, 29)
                .addComponent(separadorBase, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblData)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Sobre().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
