package view;

import java.util.logging.Level;
import java.util.logging.Logger;

import com.formdev.flatlaf.FlatDarkLaf;

import utils.Constantes;
import utils.ViewUtils;

public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JButton bProfessores = ViewUtils.criarBotao(Constantes.UIConstants.BTN_PROFESSORES, this::bProfessoresActionPerformed);
        javax.swing.JButton bAlunos = ViewUtils.criarBotao(Constantes.UIConstants.BTN_ALUNOS, this::bAlunosActionPerformed);
        javax.swing.JLabel lblSistema = ViewUtils.criarLabel(Constantes.UIConstants.TITULO_SISTEMA, "lblSistema");
        javax.swing.JMenuBar menu = ViewUtils.criarMenuBar();
        javax.swing.JMenu arquivo = ViewUtils.criarMenu(Constantes.UIConstants.MENU_PRINCIPAL, "menu");
        javax.swing.JMenuItem menuAlunos = ViewUtils.criarMenuItem(Constantes.UIConstants.GERENCIAR_ALUNOS, this::bAlunosActionPerformed, "menuAlunos");
        javax.swing.JMenuItem menuProfessores = ViewUtils.criarMenuItem(Constantes.UIConstants.GERENCIAR_PROFESSORES, this::bProfessoresActionPerformed, "menuProfessores");
        javax.swing.JMenuItem menuSobre = ViewUtils.criarMenuItem(Constantes.UIConstants.SOBRE, this::jMenuItem1ActionPerformed, "menuSobre");
        javax.swing.JMenuItem menuLeave = ViewUtils.criarMenuItem(Constantes.UIConstants.LEAVE, this::menuLeaveActionPerformed, "menuLeave");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setBackground(new java.awt.Color(51, 255, 51));
        setResizable(false);

        bProfessores.setFont(new java.awt.Font(Constantes.UIConstants.DEFAULT_FONT, 0, 18));
        bProfessores.setText("Professores");
        bProfessores.setToolTipText("CTRL+P");
        bProfessores.setAlignmentX(0.5F);

        bAlunos.setFont(new java.awt.Font(Constantes.UIConstants.DEFAULT_FONT, 0, 18));
        bAlunos.setText("Alunos");
        bAlunos.setToolTipText("CTRL+A");

        lblSistema.setFont(new java.awt.Font(Constantes.UIConstants.DEFAULT_FONT, java.awt.Font.BOLD, 14));
        lblSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSistema.setText("SisUni - Sistema de Gerenciamento Universitário");

        arquivo.setText("Arquivo");

        menuAlunos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuAlunos.setText("Gerenciamento de Alunos");
        arquivo.add(menuAlunos);

        menuProfessores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuProfessores.setText("Gerenciamento de Professores");
        arquivo.add(menuProfessores);

        menuSobre.setText("Sobre");
        arquivo.add(menuSobre);

        menuLeave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuLeave.setText("Sair");
        arquivo.add(menuLeave);

        menu.add(arquivo);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(bAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        bProfessores.getAccessibleContext().setAccessibleDescription("");
        bAlunos.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // método utilitário
    private void abrirTelaGerenciaAlunos() {
        GerenciaAlunos tela = new GerenciaAlunos();
        tela.setVisible(true);
        this.dispose();
    }

    // método utilitário
    private void abrirTelaGerenciaProfessores() {
        GerenciaProfessores tela = new GerenciaProfessores();
        tela.setVisible(true);
        this.dispose();
    }

    private void bAlunosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bAlunosActionPerformed
        assert evt != null || evt == null;

        abrirTelaGerenciaAlunos();
    }// GEN-LAST:event_bAlunosActionPerformed

    private void bProfessoresActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bProfessoresActionPerformed
        assert evt != null || evt == null;

        abrirTelaGerenciaProfessores();
    }// GEN-LAST:event_bProfessoresActionPerformed

    private void menuLeaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menuLeaveActionPerformed
        assert evt != null || evt == null;

        System.exit(0);
    }// GEN-LAST:event_menuLeaveActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
        assert evt != null || evt == null;

        Sobre tela = new Sobre();
        tela.setVisible(true);
    }// GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private static final Logger logger = Logger.getLogger(TelaPrincipal.class.getName());

    public static void main(String[] args) {
        try {
            FlatDarkLaf.setup();
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Falha ao inicializar o tema FlatDarkLaf na TelaPrincipal", e);
        }

        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
